// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<I18nEngine>>
abstract class I18NEngine implements RustOpaqueInterface {
  void addBundle({
    required String locale,
    required String namespace,
    required String jsonString,
  });

  I18NManager get inner;

  set inner(I18NManager inner);

  String diagnostics();

  factory I18NEngine({required String defaultLocale, String? fallbackLocale}) =>
      RustLib.instance.api.crateApiEngineI18NEngineNew(
        defaultLocale: defaultLocale,
        fallbackLocale: fallbackLocale,
      );

  void setDebugMode({required bool enabled});

  void setLocale({required String locale});

  String t({required String namespace, required String key, String? argsJson});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<I18nManager>>
abstract class I18NManager implements RustOpaqueInterface {}
