// i18n-node/frameworks/nuxt.ts
import { defineNuxtModule, addVitePlugin } from '@nuxt/kit';
import wasm from 'vite-plugin-wasm';
import topLevelAwait from 'vite-plugin-top-level-await';
import * as fs from 'fs';
import * as path from 'path';

function flattenKeys(obj: any, prefix = ''): string[] {
  let keys: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    const fullKey = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'object' && v !== null && !Array.isArray(v)) {
      keys.push(...flattenKeys(v, fullKey));
    } else {
      keys.push(fullKey);
    }
  }
  return keys;
}

// --- کدهای جدید: تابع تولید فایل تایپ ---
function generateDts(bundles: any, defaultLocale: string, nuxtBuildDir: string) {
  const nsData = bundles[defaultLocale] || {};
  let dts = `// Auto-generated by i18n-sdk - DO NOT EDIT\n\n`;
  
  const namespaces = Object.keys(nsData);
  if (namespaces.length === 0) return;

  // ساخت تایپ برای فضاهای نام (Namespaces)
  dts += `export type I18nNamespace = ${namespaces.map(k => `'${k}'`).join(' | ')} | (string & {});\n\n`;

  // ساخت تایپ شرطی برای کلیدها بر اساس فضای نام
  dts += `export type I18nKey<T extends I18nNamespace> =\n`;
  for (const ns of namespaces) {
    const keys = flattenKeys(nsData[ns]);
    if (keys.length > 0) {
      dts += `  T extends '${ns}' ? ${keys.map(k => `'${k}'`).join(' | ')} :\n`;
    }
  }
  dts += `  string;\n`;

  // ذخیره فایل در پوشه .nuxt تا VSCode به صورت خودکار آن را بشناسد
  const outPath = path.join(nuxtBuildDir, 'i18n-schema.d.ts');
  fs.writeFileSync(outPath, dts, 'utf-8');
}
// ------------------------------------------------

export interface ModuleOptions {
  localeDir?: string;
  fetchLocalesApi?: string;
  hardcodedLocales?: string[];
}

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'i18n-sdk-nuxt',
    configKey: 'i18nSdk',
    compatibility: { nuxt: '>=3.0.0' }
  },
  defaults: {
    localeDir: 'langs'
  },
  async setup(options: any, nuxt: any) {
    addVitePlugin(wasm());
    addVitePlugin(topLevelAwait());

    const virtualModuleId = 'virtual:i18n-sdk-bundles';
    const resolvedVirtualModuleId = '\0' + virtualModuleId;

    let availableLocales: string[] = [];
    if (options.hardcodedLocales?.length) {
      availableLocales = options.hardcodedLocales;
    } else if (options.fetchLocalesApi) {
      const res = await fetch(options.fetchLocalesApi);
      const data = await res.json();
      availableLocales = data.locales;
    }

    addVitePlugin({
      name: 'vite-plugin-i18n-sdk-auto-loader',
      resolveId(id: string) {
        if (id === virtualModuleId) return resolvedVirtualModuleId;
      },
      load(id: string) {
        if (id === resolvedVirtualModuleId) {
          const i18nDir = path.resolve(nuxt.options.rootDir, options.localeDir);
          const bundles: Record<string, Record<string, any>> = {};
          
          if (fs.existsSync(i18nDir)) {
            const detectedLocales = fs.readdirSync(i18nDir).filter((f: string) => fs.statSync(path.join(i18nDir, f)).isDirectory());
            if (!availableLocales.length) availableLocales = detectedLocales;
            
            for (const locale of availableLocales) {
              bundles[locale] = {};
              const localePath = path.join(i18nDir, locale);
              if (!fs.existsSync(localePath)) continue;
              
              const files = fs.readdirSync(localePath).filter((f: string) => f.endsWith('.json'));
              for (const file of files) {
                const namespace = file.replace('.json', '');
                const content = fs.readFileSync(path.join(localePath, file), 'utf-8');
                bundles[locale][namespace] = JSON.parse(content);
              }
            }
            
            // --- اجرای خودکار ولیدیتور تایپ‌اسکریپت ---
            // بر اساس اولین زبان (معمولاً زبان پایه مثل 'fa' یا 'en') ساختار کلیدها رو استخراج می‌کنیم
            if (availableLocales.length > 0) {
               generateDts(bundles, availableLocales[0], nuxt.options.buildDir);
            }
          }

          return `
            export const bundles = ${JSON.stringify(bundles)};
            export const locales = ${JSON.stringify(availableLocales)};
          `;
        }
      }
    });

    // تنظیمات OptimizeDeps (مشابه قبل)
    nuxt.options.vite.optimizeDeps = nuxt.options.vite.optimizeDeps || {};
    nuxt.options.vite.optimizeDeps.exclude = nuxt.options.vite.optimizeDeps.exclude || [];
    nuxt.options.vite.optimizeDeps.exclude.push('i18n-sdk');
    nuxt.options.vite.ssr = nuxt.options.vite.ssr || {};
    nuxt.options.vite.ssr.external = nuxt.options.vite.ssr.external || [];
    nuxt.options.vite.ssr.external.push('i18n-sdk');
  }
});