name: i18n_flutter
description: "A blazing fast, cross-platform i18n SDK powered by Rust and Flutter."
version: 0.2.3
homepage: https://github.com/bbhcoder/i18n
repository: https://github.com/bbhcoder/i18n

environment:
  sdk: ^3.12.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  # باز کردن محدوده ورژن برای جلوگیری از تداخل با بقیه پکیج‌ها
  flutter_rust_bridge: ^2.12.0
  plugin_platform_interface: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.example.i18n_flutter
        pluginClass: I18nFlutterPlugin
      ios:
        pluginClass: I18nFlutterPlugin
      linux:
        pluginClass: I18nFlutterPlugin
      macos:
        pluginClass: I18nFlutterPlugin
      windows:
        pluginClass: I18nFlutterPluginCApi
